services:
  client:
    container_name: client
    image: ${CI_REGISTRY_IMAGE}/client:${IMAGE_TAG}
    build:
      context: ./client/
      dockerfile: Dockerfile
    networks:
      - app-net
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8443:8443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  server:
    container_name: server
    image: ${CI_REGISTRY_IMAGE}/server:${IMAGE_TAG}
    build:
      context: ./server/
      dockerfile: Dockerfile
    networks:
      - app-net
      - db-net
    depends_on:
      db:
        condition: service_started

  db:
    container_name: mongodb
    image: mongo:8.0
    restart: always
    command: --config /etc/mongo/mongod.conf
    volumes:
      - db-data:/data/db
      - ./mongodb/mongod.conf:/etc/mongo/mongod.conf:ro
    networks:
      - db-net
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  app-net:
  db-net:
