services:
  client:
    container_name: client
    image: fitness-repository/client
    build:
      context: ./client/
      dockerfile: Dockerfile
    networks:
      - app-net
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  server:
    container_name: server
    image: fitness-repository/server
    build:
      context: ./server/
      dockerfile: Dockerfile
    networks:
      - app-net
      - db-net
    depends_on:
      db:
        condition: service_started

  db:
    container_name: mongodb
    image: mongo:8.0
    restart: always
    command: --config /etc/mongo/mongod.conf
    volumes:
      - db-data:/data/db
    networks:
      - db-net
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  app-net:
  db-net:
